### ISSUE TITLE
. P2 *** RDV *** K répond par OUI ou NON à l'invitation de rdv

### ISSUE THREAD

**Issue by SarahHevin** [SocialGouv/pass_emploi_app#50]
- [x] Lorsque K reçoit une invitation de RDV il a la possibilité d'accepter ou de refuser le créneau 
- [x] Si K accepte le RDV : il peut reconnaître sur son interface que le statut de son RDV est validé et qu'il aura bien lieu
- [x] Si K refuse le RDV : il voit apparaître des recommandations pour justifier son refus (envoyer un justificatif par mail, etc.)

- [ ] K est capable de différencier visuellement les RDV validés et ceux qu'il n'a pas accepté (grisés)
- [ ] Quand N accepte de supprimer définitivement le RDV refusé, K ne le voit plus apparaître sur son tableau de bord

Fait (en partie ?) dans UI jeune :
https://www.figma.com/file/cw7BmcozYJOal7xbecSDA7/UX-UI-Pass-Emploi?node-id=0%3A1

**Comment by isabelle-cerrutti** [comment]
Il manque les 2 dernières stories. Nous devons échanger aussi autour de l'annulation des RDV qui ne doit pas être à la main du jeune. Je bascule dans le backlog
