### ISSUE TITLE
P1 ***Tchat entre K et N*** Echanger des messages entre K et N par le biais d'une messagerie instantanée

### ISSUE THREAD

**Issue by isabelle-cerrutti** [SocialGouv/pass_emploi_app#6]
Pour le MVP, pas d'écran intermédiaire : on ne discute qu'en 1 à 1

TA 2 :
- [x] N envoie un message à K via son outil de messagerie instantanée web.
- [x] K consulte le message  de N via l'outil de messagerie instantanée de son app pass-emploi 

UI 
- [x] Ajuster l'UI de l'app pour la date, l'heure et le picto du conseiller (à supprimer)

**Comment by adgeg** [comment]
Mettre la premlière lettre au clavier automatiquement en majuscule

**Comment by adgeg** [comment]
@isabelle-cerrutti : c'est corrigé, tu pourras vérifier demain en live.

**Comment by isabelle-cerrutti** [comment]
Merci !Mais n'aurais tu pas clos par erreur l'issue #6 au lieu de la lettre dans une colonne...De : Gabriel Adgeg ***@***.***>Envoyé : lundi 16 août 2021 à 15:43À : SocialGouv/pass_emploi_appCc : Isabelle Cerrutti; MentionObjet : Re: [SocialGouv/pass_emploi_app] P1 ***Tchat entre K et N*** Echanger des messages entre K et N par le biais d'une messagerie instantanée (#6)

@isabelle-cerrutti : c'est corrigé, tu pourras vérifier demain en live.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/SocialGouv/pass_emploi_app/issues/6#issuecomment-899521882",

"url": "https://github.com/SocialGouv/pass_emploi_app/issues/6#issuecomment-899521882",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
